name: Deploy PR Preview

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get PR number
        id: pr
        run: echo "PR_NUM=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Build static site
        run: |
          mkdir -p previews/pr-${PR_NUM}
          cp public/index.php previews/pr-${PR_NUM}/index.html
          cp -r public/assets previews/pr-${PR_NUM}/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./previews
          publish_branch: gh-pages

      - name: Comment preview URL on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: preview-link
          message: |
            🚀 **Preview your changes here**:
            https://ColinMcArthur85.github.io/devsite/pr-${{ github.event.pull_request.number }}/
